# Generated by Django 3.2.8 on 2021-10-19 04:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_post_voice'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='voice',
            field=models.FileField(default=None, upload_to='voices'),
        ),
    ]
